version: '3'
services:
    store-app:
        restart: always
        container_name: store-app
        build: ./
        volumes:
            - .:/app
        ports:
            - 5000:5000
        environment:
            - PYTHONPATH=/app
            - FLASK_DEBUG=0
            - FLASK_APP=backend/app.py
        env_file:
            - .env
        command: flask run
        network_mode: 'host'